# Generated by Django 5.2 on 2025-05-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('num_rooms', models.IntegerField(blank=True, null=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='user.seller')),
            ],
        ),
    ]
