# Generated by Django 5.2 on 2025-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
