# Generated by Django 4.2.20 on 2025-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/property_images/'),
        ),
    ]
