# Generated by Django 5.2 on 2025-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
