# Generated by Django 5.2 on 2025-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_num_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
