# Generated by Django 4.2.20 on 2025-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('', 'Select type'), ('real_estate', 'Real Estate agency'), ('indivitual', 'Indivitual')], max_length=50),
        ),
    ]
