# Generated by Django 4.2.20 on 2025-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('appartment', 'Apartment'), ('block', 'Block'), ('house', 'House'), ('castle', 'Castle'), ('townhouse', 'Townhouse')], max_length=50),
        ),
    ]
