# Generated by Django 4.2.20 on 2025-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate agency'), ('indivitual', 'Indivitual')], max_length=50),
        ),
    ]
