# Generated by Django 4.2.20 on 2025-05-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Select type'), ('real_estate', 'Real Estate agency'), ('indivitual', 'Indivitual')], max_length=50),
        ),
    ]
