# Generated by Django 5.2 on 2025-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Select type'), ('real_estate', 'Real Estate agency'), ('individual', 'Individual')], max_length=50),
        ),
    ]
