# Generated by Django 5.2 on 2025-05-13 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_paymentinfo_mortgageinfo_creditcardinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgageinfo',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='creditcardinfo',
            name='payment',
        ),
        migrations.AddField(
            model_name='creditcardinfo',
            name='offer',
            field=models.OneToOneField(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_info', to='offer.purchaseoffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardinfo',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mortgageinfo',
            name='offer',
            field=models.OneToOneField(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_info', to='offer.purchaseoffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mortgageinfo',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
