# Generated by Django 5.2 on 2025-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_remove_mortgageinfo_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoffer',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='kennitala',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='postal_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='street',
            field=models.CharField(blank=True, null=True),
        ),
    ]
